# Generated by Django 4.2.1 on 2023-05-31 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_rename_extrato_movimentacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='transferencia_recebida',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transferencia',
            name='remetente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
