# Generated by Django 4.2.1 on 2023-05-31 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_movimentacao_transferencia_recebida_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacao',
            name='transferencia_recebida',
        ),
        migrations.RemoveField(
            model_name='transferencia',
            name='remetente',
        ),
    ]
